name: Pull request workflow

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  check_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Generate cache key
        run: ./scripts/checksum.sh ./ checksum.txt

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
            build-cache
          key: gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('checksum.txt') }}

      - name: googleServiceJson
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./app/google-services.json.b64 && base64 -d ./app/google-services.json.b64 > ./app/google-services.json

      - name: Run Android checks
        run: ./gradlew check --stacktrace

      - name: Upload reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2
